### ISSUE TITLE
Loose dependency allows chex version without 'warn_deprecated_function' to be installed

### ISSUE THREAD

**Issue by phcavelar** [google-deepmind/optax#995]
I was setting up and environment and optax installed with version 0.2.2, but it did not require a chex package version that has 'warn_deprecated_function', giving the following error on library import:
```python
>>> import optax
optTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/phcavelar/miniconda3/envs/multimodal/lib/python3.9/site-packages/optax/__init__.py", line 18, in <module>
    from optax import losses
  File "/home/phcavelar/miniconda3/envs/multimodal/lib/python3.9/site-packages/optax/losses/__init__.py", line 17, in <module>
    from optax.losses._classification import convex_kl_divergence
  File "/home/phcavelar/miniconda3/envs/multimodal/lib/python3.9/site-packages/optax/losses/_classification.py", line 64, in <module>
    chex.warn_deprecated_function,
AttributeError: module 'chex' has no attribute 'warn_deprecated_function'
```

I'd suggest you add as a requirement "chex>=0.1.86" for optax 0.2.2.

**Comment by phcavelar** [comment]
You already seem to have "chex>=0.1.86" as a requirement, but somehow that was ignored when I was building my environment. I'll be closing this issue but still would be good to have a look on why this happened and at least it's documented here if anyone has this issue that they can just use optax=0.2.1 to fix it.

**Comment by Miaoyuanyuan777** [comment]
it helps me! thanks!!!
